### ISSUE TITLE
crash in "bom downloadsources"

### ISSUE THREAD

**Issue by gernot-h** [sw360/capycli#46]
@Garbald reported another crash which I can also reproduce:

` poetry run python3 -m capycli bom downloadsources --nocache -i ./bom-christoph-tietz.json -url https://sw360.siemens.com -oa -t ...` leads to:

```
CaPyCli, 2.0.1 - Download source files from the URL specified in the SBOM

Loading SBOM file ./bom-christoph-tietz.json
Downloading source files to folder ./ ...
  logback-classic, 1.3.11
    URL = https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.3.11/logback-classic-1.3.11-sources.jar
    Downloading file logback-classic-1.3.11-sources.jar
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gernot/checkout/capycli/capycli/__main__.py", line 13, in <module>
    cli.main()
  File "/home/gernot/checkout/capycli/capycli/main/cli.py", line 27, in main
    app.run(argv)
  File "/home/gernot/checkout/capycli/capycli/main/application.py", line 157, in run
    self._run(argv)
  File "/home/gernot/checkout/capycli/capycli/main/application.py", line 138, in _run
    handle_bom.run_bom_command(self.options)
  File "/home/gernot/checkout/capycli/capycli/bom/handle_bom.py", line 102, in run_bom_command
    app.run(args)
  File "/home/gernot/checkout/capycli/capycli/bom/download_sources.py", line 196, in run
    self.download_sources(bom, source_folder)
  File "/home/gernot/checkout/capycli/capycli/bom/download_sources.py", line 113, in download_sources
    ext_ref = ExternalReference(
TypeError: __init__() missing 1 required keyword-only argument: 'url'
```

It seems https://github.com/sw360/capycli/blob/ad9f60d1dc1c7f8386997ff181e8ea68bdac862a/capycli/bom/download_sources.py#L117 should be moved to the constructor call in line 113.

**Comment by Garbald** [comment]
Line 117 should probably not be moved because the constructor call is conditional. But yes, the url info should be added to the constructor call.

**Comment by gernot-h** [comment]
> Line 117 should probably not be moved because the constructor call is conditional. But yes, the url info should be added to the constructor call.

You're certainly right, this was just a quick shot to make clear that the fix should be trivial. :-) If you want, feel free to create a Pull Request with your (tested) changes, by the way. :-)
